routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BagianController;
use App\Http\Controllers\AkunController;
use App\Http\Controllers\ComplaintController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\VerifikasiController;
use App\Http\Controllers\KonfirmasiController;
use App\Http\Controllers\RekapController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/statistik', function () {
    return view('statistik');
});

Auth::routes();

Route::get('/teka', function () {
    return view('teka');
});

Auth::routes();

Route::get('/login', function () {
    return view('login');
});

Auth::routes();


Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('bagian', 'BagianController'); 
Route::resource('akun', 'AkunController'); 
Route::resource('complaint', 'ComplaintController'); 
Route::resource('beranda', 'BerandaController'); 
Route::resource('verifikasi', 'VerifikasiController'); 
Route::resource('konfirmasi', 'KonfirmasiController');
Route::resource('rekap', 'RekapController');

app/Bagian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Bagian extends Model
{

    protected $table = 'bagian';
    protected $primaryKey = 'id_bagian';
    protected $fillable = ['id_bagian','bagian'];
    public 	  $timestamps = false;
}

?>

app/Http/Controllers/BagianController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Bagian;

class BagianController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bagian = Bagian::latest()->paginate(10);

        return view('bagian.index',compact('bagian'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('bagian.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'bagian'=> 'required',

        ]);

        Bagian::create($request->all());
        return redirect()->route('bagian.index')
                        ->with('berhasil','datadisimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id_bagian
     * @return \Illuminate\Http\Response
     */
    public function show(Bagian $id_bagian)
    {
        $bagian = Bagian::find($id_bagian);
        return view('bagian.show', compact('bagian'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id_bagian
     * @return \Illuminate\Http\Response
     */
    public function edit($id_bagian)
    {
        $bagian = Bagian::find($id_bagian);
        return view ('bagian.edit', compact('bagian'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id_bagian
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_bagian)
    {
         $request -> validate([
   
            'bagian' => 'required',
            
        ]);

        $bagian = Bagian::find($id_bagian)->update($request->all());

        return redirect()->route('bagian.index')
                        ->with('berhasil','data sudah disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id_bagian
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_bagian)
    {
         $bagian = Bagian::find($id_bagian)->delete();
        return redirect()->route('bagian.index')
                        ->with('berhasil','data sudah dihapus');
    }
}

resources/views/bagian/create.blade.php
@extends('adminlte::page')

@section('content')
 <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Data Mahasiswa Test</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Test data mahasiswa </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">


@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Wadooo</strong> Ada masalah dalam inputan.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Data Mahasiswa </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('bagian.store') }}" method="POST">
                   @csrf
            
                <div class="card-body">
                  <div class="form-group">
                    <label for="bagian">Bagian</label>
                    <input type="text" class="form-control" id="bagian" name="bagian" placeholder="masukan nama">
                  </div>
              
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
              
      
@endsection

resources/views/bagian/edit.blade.php
@extends('adminlte::page')

@section('content')
 <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Data bagian edit</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">edit data Unit Kerja </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">


@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Wadooo</strong> Ada masalah dalam inputan.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Data Mahasiswa </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('bagian.update',$bagian->id) }}" method="POST">
                   @csrf
                   @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="bagian">Unit Kerja</label>
                    <input type="text" class="form-control" id="bagian" name="bagian" placeholder="{{ $bagian->bagian }}">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
              
      
@endsection

resources/views/bagian/index.blade.php
@extends('adminlte::page')

@section('styles')

<!-- DataTables -->
<link rel="stylesheet" href="{{url('AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
    <!-- Content Header (Page header) -->
     <!-- /.row -->
<div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Unit Kerja</h3>
              </div>
                <div class="card-header">
                        <a class="btn btn-info btn-sm" href="{{ route('bagian.create') }}">Tambah Unit Kerja</a>
             
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif


                <table class="table table-bordered">
                    <tr>
                        <th width="20px" class="text-center">No</th>
                        <th width="20px" class="text-center">nama bagian</th>
                        <th width="280px"class="text-center">Action</th>
                    </tr>
                    @foreach ($bagian as $item)
                    <tr>
                        <td width="20px" class="text-center">{{ ++$i }}</td>
                        <td width="20px" class="text-center">{{ $item->bagian }}</td>
    

                        <td class="text-center">
                            <form action="{{ route('bagian.destroy',$item->id_bagian) }}" method="POST">

                              

             <a class="btn btn-primary btn-sm" href="{{ route('bagian.edit',$item->id_bagian) }}">Edit</a>

                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.row -->
@endsection