routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BagianController;
use App\Http\Controllers\AkunController;
use App\Http\Controllers\ComplaintController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\VerifikasiController;
use App\Http\Controllers\KonfirmasiController;
use App\Http\Controllers\RekapController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/statistik', function () {
    return view('statistik');
});

Auth::routes();

Route::get('/teka', function () {
    return view('teka');
});

Auth::routes();

Route::get('/login', function () {
    return view('login');
});

Auth::routes();


Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('bagian', 'BagianController'); 
Route::resource('akun', 'AkunController'); 
Route::resource('complaint', 'ComplaintController'); 
Route::resource('beranda', 'BerandaController'); 
Route::resource('verifikasi', 'VerifikasiController'); 
Route::resource('konfirmasi', 'KonfirmasiController');
Route::resource('rekap', 'RekapController');

app/Akun.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Akun extends Model
{

    protected $table = 'akun';
    protected $primaryKey = 'id_akun';
    protected $fillable = ['id_akun','username','password','role'];
    public 	  $timestamps = false;
}

?>

app/Http/Controllers/AkunController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Akun;

class AkunController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $akun = Akun::latest()->paginate(10);

        return view('akun.index',compact('akun'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('akun.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'username'=> 'required', 'password'=> 'required', 'role'=> 'required'

        ]);

        Akun::create($request->all());
        return redirect()->route('akun.index')
                        ->with('berhasil','datadisimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id_akun
     * @return \Illuminate\Http\Response
     */
    public function show(Akun $id_akun)
    {
        $akun = Akun::find($id_akun);
        return view('akun.show', compact('akun'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id_akun
     * @return \Illuminate\Http\Response
     */
    public function edit($id_akun)
    {
        $akun = Akun::find($id_akun);
        return view ('akun.edit', compact('akun'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id_akun
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_akun)
    {
         $request -> validate([
   
            'username'=> 'required', 'password'=> 'required', 'role'=> 'required'
            
        ]);

        $akun = Akun::find($id_akun)->update($request->all());

        return redirect()->route('akun.index')
                        ->with('berhasil','data sudah disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id_akun
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_akun)
    {
         $akun = Akun::find($id_akun)->delete();
        return redirect()->route('akun.index')
                        ->with('berhasil','data sudah dihapus');
    }
}

resources/views/akun/create.blade.php
@extends('adminlte::page')

@section('content')
 <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Akun</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Akun </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">


@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Wadooo</strong> Ada masalah dalam inputan.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Data Akun </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('akun.store') }}" method="POST">
                   @csrf
            
                <div class="card-body">
                  <div class="form-group">
                    <label for="akun">User Name</label>
                    <input type="text" class="form-control" id="akun" name="username" placeholder="masukan user name">
                    <label for="akun">Password</label>
                    <input type="text" class="form-control" id="akun" name="password" placeholder="masukan password">

                    <label for="akun">Role</label>
                    <select class="form-control" id="role" name="role">
                      <option>Admin</option>
                      <option>Pimpinan</option>
                      <option>Mahasiswa</option>
                    </select>
                  </div>


              
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
              
      
@endsection

resources/views/akun/edit.blade.php
@extends('adminlte::page')

@section('content')
 <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Edit Akun</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">edit akun </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">


@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Wadooo</strong> Ada masalah dalam inputan.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

            
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Data Akun </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('akun.update',$akun->id_akun) }}" method="POST">
                   @csrf
                   @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="akun">User Name</label>
                    <input type="text" class="form-control" id="akun" name="username" placeholder="masukan user name" value="{{$akun->username}}">
                    <label for="akun">Password</label>
                    <input type="text" class="form-control" id="akun" name="password" placeholder="masukan password" value="{{$akun->password}}">

                    <label for="akun">Role</label>
                    <select class="form-control" id="role" name="role" value="{{$akun->role}}">
                      <option>Admin</option>
                      <option>Pimpinan</option>
                      <option>Mahasiswa</option>
                    </select>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
              
      
@endsection

resources/views/akun/index.blade.php
@extends('adminlte::page')

@section('styles')

<!-- DataTables -->
<link rel="stylesheet" href="{{url('AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
    <!-- Content Header (Page header) -->
     <!-- /.row -->
<div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Akun</h3>
              </div>
                <div class="card-header">
                        <a class="btn btn-info btn-sm" href="{{ route('akun.create') }}">Tambah Akun</a>
             
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif


                <table class="table table-bordered">
                    <tr>
                        <th width="10px" class="text-center">No.</th>
                        <th width="30px" class="text-center">User Name</th>
                        <th width="30px" class="text-center">Password</th>
                        <th width="30px" class="text-center">Role</th>
                        <th width="80px" class="text-center">Aksi</th>
                    </tr>
                    @foreach ($akun as $item)
                    <tr>
                        <td width="10px" class="text-center">{{ ++$i }}</td>
                        <td width="30px" class="text-center">{{ $item->username }}</td>
                        <td width="30px" class="text-center">{{ $item->password }}</td>
                        <td width="30px" class="text-center">{{ $item->role }}</td>

    

                        <td class="text-center">
                            <form action="{{ route('akun.destroy',$item->id_akun) }}" method="POST">

                               

             <a class="btn btn-primary btn-sm" href="{{ route('akun.edit',$item->id_akun) }}">Edit</a>

                                @csrf
                                @method('DELETE')

                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.row -->
@endsection