routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BagianController;
use App\Http\Controllers\AkunController;
use App\Http\Controllers\ComplaintController;
use App\Http\Controllers\BerandaController;
use App\Http\Controllers\VerifikasiController;
use App\Http\Controllers\KonfirmasiController;
use App\Http\Controllers\RekapController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/statistik', function () {
    return view('statistik');
});

Auth::routes();

Route::get('/teka', function () {
    return view('teka');
});

Auth::routes();

Route::get('/login', function () {
    return view('login');
});

Auth::routes();


Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('bagian', 'BagianController'); 
Route::resource('akun', 'AkunController'); 
Route::resource('complaint', 'ComplaintController'); 
Route::resource('beranda', 'BerandaController'); 
Route::resource('verifikasi', 'VerifikasiController'); 
Route::resource('konfirmasi', 'KonfirmasiController');
Route::resource('rekap', 'RekapController');

app/Complaint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Complaint extends Model
{
    protected $table = 'complaint';
    protected $primaryKey = 'id_complaint';
    protected $fillable = ['id_complaint','username','unitkerja','subjek','uraian','saransolusi','status'];
    public 	  $timestamps = false;
}

app/Http/Controllers/ComplaintController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Complaint;
use App\Bagian;

class ComplaintController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $complaint = Complaint::latest()->paginate(10);

        return view('complaint.index',compact('complaint'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    public function store(Request $request)
    {
        $request->validate([

            'username'=> 'required', 'unitkerja'=> 'required', 'subjek'=> 'required', 'uraian'=> 'required', 'saransolusi'=> 'required', 'status'=> 'Belum Ditanggapi'


        ]);

        Complaint::create($request->all());
        return redirect()->route('verifikasi.index')
                        ->with('berhasil','datadisimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id_complaint
     * @return \Illuminate\Http\Response
     */
    public function show(Complaint $id_complaint)
    {
        $complaint = Complaint::find($id_complaint);
        return view('complaint.show', compact('complaint'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id_complaint
     * @return \Illuminate\Http\Response
     */
    public function edit($id_complaint)
    {
        $complaint = Complaint::find($id_complaint);
        return view ('complaint.edit', compact('complaint'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id_complaint
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_complaint)
    {
         $request -> validate([
   
             'status'=> 'required'
            
        ]);

        $complaint = Complaint::find($id_complaint)->update($request->all());

        return redirect()->route('complaint.index')
                        ->with('berhasil','data sudah disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id_complaint
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_complaint)
    {
         $complaint = Complaint::find($id_complaint)->delete();
        return redirect()->route('complaint.index')
                        ->with('berhasil','data sudah dihapus');
    }

    public function tampilbagian($id_bagian)
    {
        $data = Bagian::latest()->paginate(10);

        return view('bagian.index',compact('bagian'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
   

}

resources/views/complaint/index.blade.php
@extends('adminlte::page')

@section('styles')

<!-- DataTables -->
<link rel="stylesheet" href="{{url('AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endsection

@section('content')
    <!-- Content Header (Page header) -->
     <!-- /.row -->
<div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">E-Complaint</h3>
              </div>
               
              <!-- /.card-header -->
               <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Complaint Mahasiswa </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{ route('complaint.store') }}" method="POST">
                   @csrf
            
                <div class="card-body">
                  @if ($errors->any())
                      <div class="alert alert-danger">
                          <strong>Whoops!</strong> sing baleg atuh euyyyyyy.<br><br>
                          <ul>
                              @foreach ($errors->all() as $error)
                                  <li>{{ $error }}</li>
                              @endforeach
                          </ul>
                      </div>
                  @endif
                  <div class="form-group">
                    <label for="complaint">User Name</label>
                    <input type="text" class="form-control" id="complaint" name="username" placeholder="">
                    <label for="complaint">Unit Kerja</label>
                     <select class="form-control" id="complaint" name="unitkerja">
                      <option>Akademik</option>
                      <option>Tata Usaha/Umum</option>
                      <option>SDM/Kepegawaian</option>
                      <option>Perlengkapan/Fasilitas</option>
                      <option>Kemahasiswaan</option>
                      <option>Keuangan</option>
                      <option>Sistem Informasi</option>
                    </select>
                    <label for="complaint">Subjek</label>
                    <input type="text" class="form-control" id="complaint" name="subjek" placeholder="">
                    <label for="complaint">Uraian</label>
                    <input type="text" class="form-control" id="complaint" name="uraian" placeholder="">
                    <label for="complaint">Saran/Solusi</label>
                    <input type="text" class="form-control" id="complaint" name="saransolusi" placeholder="">
                   
                   

                   
                  </div>


              
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>


             

                                @csrf
                                @method('DELETE')

                               
                            </form>
                        </td>
                    </tr>

                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.row -->
@endsection